AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Template to create Route Tables for a VPC

Parameters:
  VpcId:
    Type: String
    Description: The ID of the VPC where the Route Tables will be created

  InternetGatewayId:
    Type: String
    Description: The ID of the Internet Gateway for the public route

Resources:
  PublicRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: PublicRouteTable

  DefaultRoute:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGatewayId

  PrivateRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: PrivateRouteTable

Outputs:
  PublicRouteTableId:
    Description: The ID of the public route table
    Value: !Ref PublicRouteTable

  PrivateRouteTableId:
    Description: The ID of the private route table
    Value: !Ref PrivateRouteTable
