AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Template to create Public and Private Subnets for a VPC

Resources:
  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !ImportValue VPC1Stack-VPCId
      CidrBlock: "10.0.1.0/24"  # Directly assigned CIDR block
      AvailabilityZone: !Select [0, !GetAZs ""]  # Automatically selects the first AZ in the region
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-PublicSubnet"

  PrivateSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !ImportValue VPC1Stack-VPCId
      CidrBlock: "10.0.2.0/24"  # Directly assigned CIDR block
      AvailabilityZone: !Select [1, !GetAZs ""]  # Automatically selects the second AZ in the region
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-PrivateSubnet"

  PublicSubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !ImportValue RouteTableStack-PublicRouteTableId

  PrivateSubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !ImportValue RouteTableStack-PrivateRouteTableId

  PublicSubnetNetworkAclAssociation:
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
    Properties:
      SubnetId: !Ref PublicSubnet
      NetworkAclId: !ImportValue NACLStack-NetworkACLId

  PrivateSubnetNetworkAclAssociation:
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
    Properties:
      SubnetId: !Ref PrivateSubnet
      NetworkAclId: !ImportValue NACLStack-NetworkACLId"
