AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Template to create a VPC

Parameters:
  VpcCidr:
    Type: String
    Description: The CIDR block for the VPC
    Default: "10.0.0.0/16"  # ✅ Set a default CIDR block to prevent errors

  EnableDnsSupport:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Enable DNS support in the VPC

  EnableDnsHostnames:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Enable DNS hostnames in the VPC

  InstanceTenancy:
    Type: String
    Default: "default"
    AllowedValues: ["default", "dedicated", "host"]
    Description: The instance tenancy attribute for the VPC

  VpcTags:
    Type: List<String>
    Description: The tags to apply to the VPC
    Default: ""

  InternetGatewayTags:
    Type: List<String>
    Description: The tags to apply to the Internet Gateway
    Default: ""

Resources:
  # Create the VPC
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref VpcCidr  # ✅ Will now always have a valid value
      EnableDnsSupport: !Ref EnableDnsSupport
      EnableDnsHostnames: !Ref EnableDnsHostnames
      InstanceTenancy: !Ref InstanceTenancy
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-VPC"

  # Create an Internet Gateway (IGW)
  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-IGW"

  # Attach the Internet Gateway to the VPC
  AttachInternetGateway:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

Outputs:
  # Output the VPC ID for reference in other stacks
  VPCId:
    Description: The VPC Id
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCId"

  # Output the Internet Gateway ID for reference in other stacks
  InternetGatewayId:
    Description: The Internet Gateway Id
    Value: !Ref InternetGateway
    Export:
      Name: !Sub "${AWS::StackName}-InternetGatewayId"
