AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Template to create a Network ACL for a VPC

Parameters:
  VpcId:
    Type: String
    Description: The ID of the VPC where the Network ACL will be created

Resources:
  NetworkACL:
    Type: "AWS::EC2::NetworkAcl"
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: VPC-NetworkACL

  NetworkACLInboundRule:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref NetworkACL
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: "0.0.0.0/0"

  NetworkACLOutboundRule:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref NetworkACL
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: "0.0.0.0/0"

Outputs:
  NetworkACLId:
    Description: The ID of the created Network ACL
    Value: !Ref NetworkACL
    Export:
      Name: !Sub "${AWS::StackName}-NetworkACLId"
